[tools]
rojo = "rojo-rbx/rojo@7.4.0-rc3"
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/StyLua@0.19.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.2.1"
