[package]
name = "hex-interactive/chainlink"
version = "1.0.0-rc1"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"
private = true
exclude = ["**"]
include = [
	"default.project.json",
	"src",
	"src/**",
	".luaurc",
	"wally.toml",
	"LICENSE",
	"README.md",
]
