[package]
name = "hex-interactive/chainlink"
description = "DataModel-driven logic and control system for Roblox"
version = "0.1.2"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"

[packages]
Chain = "hex-interactive/chain@0.1.0"
