import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  chainlink: [{type: 'autogenerated', dirName: 'chainlink'}],
  chain: [{type: 'autogenerated', dirName: 'chain'}],
};

export default sidebars;
